apiVersion: v1
kind: Service 
metadata: 
  name: nginx-cluster-ip
spec: 
  typr: ClusterIP 
  selector: 
    app: web 


  ports: 
    - port: 8080    #service port 
      targetPort: 3200    #pod/container port